# Generated by Django 4.0 on 2022-01-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('apps', '0003_booing_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booing_details',
            new_name='booking_details',
        ),
    ]
