# Generated by Django 4.0 on 2022-01-19 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('apps', '0004_rename_booing_details_booking_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
