# Generated by Django 4.0 on 2022-01-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_booking_details_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking_details',
        ),
    ]
