# Generated by Django 4.0 on 2022-01-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_delete_booking_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_date', models.CharField(max_length=100)),
                ('slot', models.CharField(max_length=50)),
                ('doc_name', models.CharField(max_length=50)),
            ],
        ),
    ]
