# Generated by Django 4.0.1 on 2022-01-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('phone_number', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
