# Generated by Django 4.0.1 on 2022-02-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_user_detls_delete_user_det'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detls',
            old_name='user_id',
            new_name='user_ids',
        ),
    ]
