# Generated by Django 4.0.1 on 2022-02-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_rename_user_id_user_detls_user_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('nos', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
