# Generated by Django 4.0.1 on 2022-02-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='nos',
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
