# Generated by Django 4.0.1 on 2022-02-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_med_history_p_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
